name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  push:
    branches:
      - main

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update WakaTime stats
        uses: wakatime/action@v1
        with:
          api_key: ${{ secrets.WAKATIME_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
